package com.conversational.system.application.chat;

import com.conversational.system.application.entities.conversation.AgentConversation;
import com.conversational.system.application.entities.conversation.Conversation;
import com.conversational.system.application.entities.conversation.Message;
import com.conversational.system.application.entities.conversation.repositories.AgentConversationRepository;
import com.conversational.system.application.entities.conversation.repositories.ConversationRepository;
import com.conversational.system.application.entities.conversation.repositories.MessageRepository;
import com.conversational.system.application.entities.user.User;
import com.conversational.system.application.entities.user.UserRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;

import java.util.Base64;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration test for visualization_report persistence and retrieval.
 * Tests that PNG files generated by sandbox are properly stored and retrieved
 * as base64 in JSON.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:postgresql://localhost:5432/test_db",
        "spring.datasource.username=user",
        "spring.datasource.password=password",
        "spring.jpa.hibernate.ddl-auto=create-drop"
})
public class MessageVisualizationTest {

    @Autowired
    private MessageRepository messageRepository;

    @Autowired
    private ConversationRepository conversationRepository;

    @Autowired
    private AgentConversationRepository agentConversationRepository;

    @Autowired
    private UserRepository userRepository;

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    public void testVisualizationReportWithGeneratedFiles() throws Exception {
        // Create test user
        User user = new User();
        user.setEmail("test@example.com");
        user.setUsername("testuser");
        user.setPasswordHash("hash");
        user = userRepository.save(user);

        // Create conversation
        Conversation conversation = new Conversation();
        conversation.setUser(user);
        conversation.setTitle("Test Conversation");
        conversation.setCreatedAt(java.time.LocalDateTime.now());
        conversation.setUpdatedAt(java.time.LocalDateTime.now());
        conversation = conversationRepository.save(conversation);

        // Create agent conversation
        AgentConversation agentConversation = new AgentConversation();
        agentConversation.setConversation(conversation);
        agentConversation.setAgentType("visualizer_agent");
        agentConversation.setCreatedAt(java.time.LocalDateTime.now());
        agentConversation.setUpdatedAt(java.time.LocalDateTime.now());
        agentConversation = agentConversationRepository.save(agentConversation);

        // Simulate visualization_report with generated PNG file
        byte[] pngData = createMinimalPNG();
        String base64Image = Base64.getEncoder().encodeToString(pngData);

        Map<String, Object> visualizationReport = Map.of(
                "type", "visualization_report",
                "content", "Here is your plot visualization",
                "generatedFiles", Map.of(
                        "plot.png", base64Image));

        String visualizationJson = objectMapper.writeValueAsString(visualizationReport);

        // Save message with visualization report
        Message message = new Message(agentConversation, "assistant", visualizationJson, "test-job-123");
        message = messageRepository.save(message);

        // Retrieve message from database
        Message retrievedMessage = messageRepository.findById(message.getId()).orElseThrow();

        // Parse JSON content
        JsonNode jsonNode = objectMapper.readTree(retrievedMessage.getContent());

        // Verify structure
        assertThat(jsonNode.has("type")).isTrue();
        assertThat(jsonNode.get("type").asText()).isEqualTo("visualization_report");
        assertThat(jsonNode.has("generatedFiles")).isTrue();

        // Verify generated files
        JsonNode generatedFiles = jsonNode.get("generatedFiles");
        assertThat(generatedFiles.has("plot.png")).isTrue();

        // Verify base64 encoding
        String retrievedBase64 = generatedFiles.get("plot.png").asText();
        assertThat(retrievedBase64).isNotEmpty();

        // Decode and verify it's the same PNG
        byte[] decodedPng = Base64.getDecoder().decode(retrievedBase64);
        assertThat(decodedPng).isEqualTo(pngData);
        assertThat(decodedPng[0]).isEqualTo((byte) 0x89); // PNG signature
        assertThat(decodedPng[1]).isEqualTo((byte) 0x50); // PNG signature 'P'
        assertThat(decodedPng[2]).isEqualTo((byte) 0x4E); // PNG signature 'N'
        assertThat(decodedPng[3]).isEqualTo((byte) 0x47); // PNG signature 'G'
    }

    @Test
    public void testMultipleGeneratedFiles() throws Exception {
        // Create test user
        User user = new User();
        user.setEmail("test2@example.com");
        user.setUsername("testuser2");
        user.setPasswordHash("hash");
        user = userRepository.save(user);

        // Create conversation
        Conversation conversation = new Conversation();
        conversation.setUser(user);
        conversation.setTitle("Test Conversation 2");
        conversation.setCreatedAt(java.time.LocalDateTime.now());
        conversation.setUpdatedAt(java.time.LocalDateTime.now());
        conversation = conversationRepository.save(conversation);

        // Create agent conversation
        AgentConversation agentConversation = new AgentConversation();
        agentConversation.setConversation(conversation);
        agentConversation.setAgentType("visualizer_agent");
        agentConversation.setCreatedAt(java.time.LocalDateTime.now());
        agentConversation.setUpdatedAt(java.time.LocalDateTime.now());
        agentConversation = agentConversationRepository.save(agentConversation);

        // Create multiple files
        byte[] png1 = createMinimalPNG();
        byte[] png2 = new byte[] { 0x50, 0x4E, 0x47, 0x21 }; // Different data

        Map<String, Object> visualizationReport = Map.of(
                "type", "visualization_report",
                "content", "Multiple visualizations generated",
                "generatedFiles", Map.of(
                        "chart1.png", Base64.getEncoder().encodeToString(png1),
                        "chart2.png", Base64.getEncoder().encodeToString(png2)));

        String visualizationJson = objectMapper.writeValueAsString(visualizationReport);
        Message message = new Message(agentConversation, "assistant", visualizationJson, "test-job-456");
        message = messageRepository.save(message);

        // Retrieve and verify
        Message retrievedMessage = messageRepository.findById(message.getId()).orElseThrow();
        JsonNode jsonNode = objectMapper.readTree(retrievedMessage.getContent());
        JsonNode generatedFiles = jsonNode.get("generatedFiles");

        assertThat(generatedFiles.size()).isEqualTo(2);
        assertThat(generatedFiles.has("chart1.png")).isTrue();
        assertThat(generatedFiles.has("chart2.png")).isTrue();

        // Verify both files can be decoded
        byte[] decoded1 = Base64.getDecoder().decode(generatedFiles.get("chart1.png").asText());
        byte[] decoded2 = Base64.getDecoder().decode(generatedFiles.get("chart2.png").asText());

        assertThat(decoded1).isEqualTo(png1);
        assertThat(decoded2).isEqualTo(png2);
    }

    /**
     * Creates a minimal valid PNG file (1x1 transparent pixel).
     */
    private byte[] createMinimalPNG() {
        // PNG signature + minimal IHDR, IDAT, IEND chunks for 1x1 transparent image
        return new byte[] {
                (byte) 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
                0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR chunk
                0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
                0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, (byte) 0xC4, (byte) 0x89,
                0x00, 0x00, 0x00, 0x0A, 0x49, 0x44, 0x41, 0x54, // IDAT chunk
                0x78, (byte) 0x9C, 0x63, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01,
                0x0D, 0x0A, 0x2D, (byte) 0xB4,
                0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, // IEND chunk
                (byte) 0xAE, 0x42, 0x60, (byte) 0x82
        };
    }
}
